**BRFSS Risk Factors for Heart Disease Data EDA**

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/brfss/brfss_survey_data_2024.csv")

# print first entries
df.head()

# number of rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 457670
Number of columns: 301

In [7]:
# print all column names
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

# print names of columns and stats on each column 
eda_table = pd.DataFrame({
    "feature": df.columns,
    "dtype": df.dtypes.astype(str),
    "unique_values": df.nunique(dropna=False).values,
    "missing_count": df.isna().sum().values,
    "missing_percent": (df.isna().mean().values * 100).round(2)
})

eda_table = eda_table.sort_values("missing_percent", ascending=False)
eda_table.to_csv("eda_basics_table.csv", index=False)

1. _STATE
2. FMONTH
3. IDATE
4. IMONTH
5. IDAY
6. IYEAR
7. DISPCODE
8. SEQNO
9. _PSU
10. CTELENM1
11. PVTRESD1
12. COLGHOUS
13. STATERE1
14. CELPHON1
15. LADULT1
16. NUMADULT
17. RESPSLC1
18. LANDSEX3
19. SAFETIME
20. CTELNUM1
21. CELLFON5
22. CADULT1
23. CELLSEX3
24. PVTRESD3
25. CCLGHOUS
26. CSTATE1
27. LANDLINE
28. HHADULT
29. SEXVAR
30. GENHLTH
31. PHYSHLTH
32. MENTHLTH
33. POORHLTH
34. PRIMINS2
35. PERSDOC3
36. MEDCOST1
37. CHECKUP1
38. EXERANY2
39. LASTDEN4
40. RMVTETH4
41. CVDINFR4
42. CVDCRHD4
43. CVDSTRK3
44. ASTHMA3
45. ASTHNOW
46. CHCSCNC1
47. CHCOCNC1
48. CHCCOPD3
49. ADDEPEV3
50. CHCKDNY2
51. HAVARTH4
52. DIABETE4
53. DIABAGE4
54. MARITAL
55. EDUCA
56. RENTHOM1
57. NUMHHOL4
58. NUMPHON4
59. CPDEMO1C
60. VETERAN3
61. EMPLOY1
62. CHILDREN
63. INCOME3
64. PREGNANT
65. WEIGHT2
66. HEIGHT3
67. DEAF
68. BLIND
69. DECIDE
70. DIFFWALK
71. DIFFDRES
72. DIFFALON
73. HADMAM
74. HOWLONG
75. CERVSCRN
76. CRVCLCNC
77. CRVCLPAP
78. CRVCLHPV
79. HADHYST2
80. HADSIGM4
81. COLNSIGM
82. COLNTES1
83. SIGMTES1
84. LASTSIG4
85. COLNCNCR
86. VIRCOLO1
87. VCLNTES2
88. SMALSTOL
89. STOLTEST
90. STOOLDN2
91. BLDSTFIT
92. SDNATES1
93. SMOKE100
94. SMOKDAY2
95. USENOW3
96. ECIGNOW3
97. LCSFIRST
98. LCSNUMCG
99. LCSCTSC1
100. LCSSCNCR
101. LCSCTWHN
102. ALCDAY4
103. AVEDRNK4
104. DRNK3GE5
105. MAXDRNKS
106. FLUSHOT7
107. FLSHTMY3
108. IMFVPLA5
109. PNEUVAC4
110. HIVTST7
111. HIVTSTD3
112. HIVRISK5
113. PDIABTS1
114. PREDIAB2
115. DIABTYPE
116. INSULIN1
117. CHKHEMO3
118. EYEEXAM1
119. DIABEYE1
120. DIABEDU1
121. FEETSORE
122. ARTHEXER
123. SHINGLE2
124. HPVADVC4
125. HPVADSH1
126. TETANUS1
127. CNCRDIFF
128. CNCRAGE
129. CNCRTYP2
130. CSRVTRT3
131. CSRVDOC1
132. CSRVSUM
133. CSRVRTRN
134. CSRVINST
135. CSRVINSR
136. CSRVDEIN
137. CSRVCLIN
138. CSRVPAIN
139. CSRVCTL2
140. PSATEST1
141. PSATIME1
142. PCPSARS2
143. PSASUGS1
144. PCSTALK2
145. CIMEMLO1
146. CDWORRY
147. CDDISCU1
148. CDHOUS1
149. CDSOCIA1
150. CAREGIV1
151. CRGVREL5
152. CRGVPRB4
153. CRGVALZD
154. CRGVNURS
155. CRGVPER2
156. CRGVHOU2
157. CRGVHRS2
158. CRGVLNG2
159. ACEDEPRS
160. ACEDRINK
161. ACEDRUGS
162. ACEPRISN
163. ACEDIVRC
164. ACEPUNCH
165. ACEHURT1
166. ACESWEAR
167. ACETOUCH
168. ACETTHEM
169. ACEHVSEX
170. ACEADSAF
171. ACEADNED
172. LSATISFY
173. EMTSUPRT
174. SDLONELY
175. SDHEMPLY
176. FOODSTMP
177. SDHFOOD1
178. SDHBILLS
179. SDHUTILS
180. SDHTRNSP
181. HOWSAFE1
182. MARIJAN1
183. MARJSMOK
184. MARJEAT
185. MARJVAPE
186. MARJDAB
187. MARJOTHR
188. USEMRJN4
189. LASTSMK2
190. STOPSMK2
191. MENTCIGS
192. MENTECIG
193. HEATTBCO
194. SSBSUGR2
195. SSBFRUT3
196. FIREARM5
197. GUNLOAD
198. LOADULK2
199. RCSGEND1
200. RCSXBRTH
201. RCSRLTN2
202. CASTHDX2
203. CASTHNO2
204. SOMALE
205. SOFEMALE
206. HADSEX
207. PFPPRVN4
208. TYPCNTR9
209. NOBCUSE8
210. QSTVER
211. QSTLANG
212. HPVDSHT
213. ICFQSTVR
214. _METSTAT
215. _URBSTAT
216. MSCODE
217. _STSTR
218. _STRWT
219. _RAWRAKE
220. _WT2RAKE
221. _IMPRACE
222. _CHISPNC
223. _CRACE1
224. CAGEG
225. _CLLCPWT
226. _DUALUSE
227. _DUALCOR
228. _LLCPWT2
229. _LLCPWT
230. _RFHLTH
231. _PHYS14D
232. _MENT14D
233. _HLTHPL2
234. _HCVU654
235. _TOTINDA
236. _EXTETH3
237. _ALTETH3
238. _DENVST3
239. _MICHD
240. _LTASTH1
241. _CASTHM1
242. _ASTHMS1
243. _DRDXAR2
244. _MRACE1
245. _HISPANC
246. _RACE
247. _RACEG21
248. _RACEGR3
249. _RACEPRV
250. _SEX
251. _AGEG5YR
252. _AGE65YR
253. _AGE80
254. _AGE_G
255. HTIN4
256. HTM4
257. WTKG3
258. _BMI5
259. _BMI5CAT
260. _RFBMI5
261. _CHLDCNT
262. _EDUCAG
263. _INCOMG1
264. _RFMAM23
265. _MAM402Y
266. _CRVSCRN
267. _RFPAP37
268. _HPV5YR1
269. _PAPHPV1
270. _HADCOLN
271. _CLNSCP2
272. _HADSIGM
273. _SGMSCP2
274. _SGMS102
275. _RFBLDS6
276. _STOLDN2
277. _VIRCOL2
278. _SBONTI2
279. _CRCREC3
280. _SMOKER3
281. _RFSMOK3
282. _CURECI3
283. LCSLAST_
284. LCSNUMC_
285. _LCSAGE
286. _LCSYSMK
287. _PACKDAY
288. _PACKYRS
289. _LCSYQTS
290. _LCSSMKG
291. _LCSELIG
292. _LCSCTSN
293. _LCSPSTF
294. DRNKANY6
295. DROCDY4_
296. _RFBING6
297. _DRNKWK3
298. _RFDRHV9
299. _FLSHOT7
300. _PNEUMO3
301. _AIDTST4

In [8]:
eda_numerical_summary = df.describe()
eda_numerical_summary.to_csv("eda_numerical_summary.csv", index=False)

Useful columns:   
**_MICHD** is "Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)": 1=Yes, 2=No    
**CVDINFR4** is "(Ever told) you had a heart attack, also called a myocardial infarction?"  
**CVDCRHD4** is "(Ever told) (you had) angina or coronary heart disease?"

In [ ]:
# function that for each feature calulates the percentage of people in each category that have heart disease
def heart_disease_rate_by_feature(data, feature, target="_MICHD"):
    if feature not in data.columns:
        raise ValueError(f"{feature} is not in the dataframe columns.")
    
    if target not in data.columns:
        raise ValueError(f"{target} is not in the dataframe columns.")

    temp = data[[feature, target]].copy()
    temp = temp[temp[target].isin([1, 2])]
    temp = temp.dropna(subset=[feature])

    summary = (
        temp
        .groupby(feature)
        .agg(
            total_people=(target, "count"),
            heart_disease_cases=(target, lambda x: (x == 1).sum())
        )
        .reset_index()
    )

    summary["heart_disease_percent"] = (
        summary["heart_disease_cases"] / summary["total_people"] * 100
    ).round(2)

    summary = summary.rename(columns={feature: "feature_value"})

    summary.insert(0, "feature", feature)

    summary = summary.sort_values(
        "heart_disease_percent",
        ascending=False
    )

    return summary

**Variables that would be useful to include:**   
Demographics:  
_SEX : Sex  
_AGEG5YR : Age  
EDUCA : Education level
INCOME3 : Income 
EMPLOY1 : Employment status 
MARITAL : Marital status
RENTHOM1 : Own or rent home  

General Health:   
GENHLTH : "Would you say that in general your health is: good, ok, ..."
or
_RFHLTH : "Would you say that in general your health is excellent, very good, good, fair, or poor?"  
CHECKUP1 : "Time since last routine checkup"

Stats:  
HEIGHT3 : Height  
WEIGHT2 : Weight (Could use to calulate BMI)  

Lifestyle:  
SMOKE100 : "Have you smoked at least 100 cigarettes in your entire life?   [Note:  5 packs = 100 cigarettes]"  
SMOKDAY2 : “Do you now smoke cigarettes every day, some days, or not at all?”   
ECIGNOW3 : "Would you say you have never used e-cigarettes or other electronic vaping products in your entire life or now use them every day, use them some days, or used them in the past but do not currently use them at all?"    
USENOW3 :  "Current use of chewing tobacco, snuff, or snus"  
ALCDAY4 : "During the past 30 days, how many days per week or per month did you have at least one drink of any alcoholic beverage?  (A 40 ounce beer would count as 3 drinks, or a cocktail drink with 2 shots would count as 2 drinks.)"   

Medical History:  
DIABETE4 : “Ever told you had diabetes?”   
CHCKDNY2 : “Ever told you had kidney disease?”  
CVDSTRK3 : “Ever told you had a stroke?”  
CHCCOPD3 : “Ever told you had COPD, emphysema, or chronic bronchitis?”  
ADDEPEV3 : “Ever told you had a depressive disorder?”  
HAVARTH4 : “Ever told you had some form of arthritis?”

In [21]:
predictors = [
    "_SEX",
    "_AGEG5YR",
    "EDUCA",
    "INCOME3",
    "EMPLOY1",
    "MARITAL",
    "RENTHOM1",
    "GENHLTH",
    "_RFHLTH",
    "CHECKUP1",
    "HEIGHT3",
    "WEIGHT2",
    "SMOKE100",
    "SMOKDAY2",
    "ECIGNOW3",
    "USENOW3",
    "ALCDAY4",
    "DIABETE4",
    "CHCKDNY2",
    "CVDSTRK3",
    "CHCCOPD3",
    "ADDEPEV3",
    "HAVARTH4"
]

heart_disease_dfs = {}

for predictor in predictors:
    heart_disease_dfs[predictor] = heart_disease_rate_by_feature(df, predictor)

for predictor, result_df in heart_disease_dfs.items():
    print(f"\nResults for {predictor}")
    display(result_df)

Results for _SEX

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,_SEX,1.0,214790,24530,11.42
1,_SEX,2.0,237674,17808,7.49

Results for _AGEG5YR

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
12,_AGEG5YR,13.0,40715,9336,22.93
11,_AGEG5YR,12.0,36185,6997,19.34
10,_AGEG5YR,11.0,44268,6925,15.64
9,_AGEG5YR,10.0,47220,6038,12.79
8,_AGEG5YR,9.0,42960,4575,10.65
7,_AGEG5YR,8.0,34604,2838,8.20
13,_AGEG5YR,14.0,8023,581,7.24
6,_AGEG5YR,7.0,31403,1894,6.03
5,_AGEG5YR,6.0,28757,1088,3.78
4,_AGEG5YR,5.0,30669,768,2.50
3,_AGEG5YR,4.0,28593,499,1.75
2,_AGEG5YR,3.0,26070,359,1.38
1,_AGEG5YR,2.0,23542,220,0.93
0,_AGEG5YR,1.0,29455,220,0.75

Results for EDUCA

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
2,EDUCA,3.0,16760,2276,13.58
1,EDUCA,2.0,8951,1084,12.11
4,EDUCA,5.0,119463,12618,10.56
3,EDUCA,4.0,114133,12004,10.52
0,EDUCA,1.0,706,68,9.63
5,EDUCA,6.0,190252,14133,7.43
6,EDUCA,9.0,2194,155,7.06

Results for INCOME3

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
1,INCOME3,2.0,10274,1786,17.38
3,INCOME3,4.0,19472,3096,15.90
2,INCOME3,3.0,13379,2053,15.34
4,INCOME3,5.0,41165,5219,12.68
0,INCOME3,1.0,10032,1111,11.07
5,INCOME3,6.0,49138,5359,10.91
12,INCOME3,99.0,40342,4075,10.10
6,INCOME3,7.0,60256,5713,9.48
11,INCOME3,77.0,36100,3302,9.15
7,INCOME3,8.0,51410,4087,7.95
8,INCOME3,9.0,55577,3312,5.96
9,INCOME3,10.0,26593,1314,4.94
10,INCOME3,11.0,29610,1291,4.36

Results for EMPLOY1

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
7,EMPLOY1,8.0,26938,5777,21.45
6,EMPLOY1,7.0,144777,24524,16.94
2,EMPLOY1,3.0,8799,785,8.92
8,EMPLOY1,9.0,4896,329,6.72
1,EMPLOY1,2.0,38811,2410,6.21
4,EMPLOY1,5.0,17615,1014,5.76
3,EMPLOY1,4.0,10697,525,4.91
0,EMPLOY1,1.0,185298,6612,3.57
5,EMPLOY1,6.0,11386,130,1.14

Results for MARITAL

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
2,MARITAL,3.0,48168,8952,18.58
1,MARITAL,2.0,57986,7284,12.56
3,MARITAL,4.0,9277,954,10.28
0,MARITAL,1.0,227528,20436,8.98
6,MARITAL,9.0,4008,225,5.61
4,MARITAL,5.0,83902,3569,4.25
5,MARITAL,6.0,21588,918,4.25

Results for RENTHOM1

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,RENTHOM1,1.0,309674,31239,10.09
1,RENTHOM1,2.0,116730,9225,7.90
3,RENTHOM1,7.0,1044,81,7.76
2,RENTHOM1,3.0,22330,1611,7.21
4,RENTHOM1,9.0,2680,182,6.79

Results for GENHLTH

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
4,GENHLTH,5.0,21470,6772,31.54
3,GENHLTH,4.0,66479,12347,18.57
5,GENHLTH,7.0,860,127,14.77
6,GENHLTH,9.0,338,41,12.13
2,GENHLTH,3.0,154392,14455,9.36
1,GENHLTH,2.0,144984,7007,4.83
0,GENHLTH,1.0,63938,1589,2.49

Results for _RFHLTH

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
1,_RFHLTH,2.0,87949,19119,21.74
2,_RFHLTH,9.0,1201,168,13.99
0,_RFHLTH,1.0,363314,23051,6.34

Results for CHECKUP1

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,CHECKUP1,1.0,365772,39047,10.68
4,CHECKUP1,7.0,4460,322,7.22
6,CHECKUP1,9.0,634,40,6.31
1,CHECKUP1,2.0,39328,1697,4.31
5,CHECKUP1,8.0,2729,93,3.41
2,CHECKUP1,3.0,21293,617,2.90
3,CHECKUP1,4.0,18248,522,2.86

Results for HEIGHT3

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
165,HEIGHT3,9209.0,1,1,100.0
171,HEIGHT3,9815.0,1,1,100.0
5,HEIGHT3,306.0,4,3,75.0
6,HEIGHT3,307.0,2,1,50.0
55,HEIGHT3,708.0,2,1,50.0
...,...,...,...,...,...
166,HEIGHT3,9240.0,1,0,0.0
168,HEIGHT3,9251.0,1,0,0.0
167,HEIGHT3,9249.0,1,0,0.0
170,HEIGHT3,9254.0,3,0,0.0
169,HEIGHT3,9252.0,1,0,0.0

Results for WEIGHT2

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
626,WEIGHT2,9352.0,1,1,100.0
604,WEIGHT2,9181.0,1,1,100.0
347,WEIGHT2,397.0,1,1,100.0
442,WEIGHT2,531.0,1,1,100.0
621,WEIGHT2,9274.0,1,1,100.0
...,...,...,...,...,...
607,WEIGHT2,9186.0,2,0,0.0
608,WEIGHT2,9187.0,1,0,0.0
625,WEIGHT2,9330.0,1,0,0.0
0,WEIGHT2,50.0,14,0,0.0
1,WEIGHT2,51.0,1,0,0.0

Results for SMOKE100

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,SMOKE100,1.0,165116,22593,13.68
2,SMOKE100,7.0,1997,219,10.97
3,SMOKE100,9.0,465,42,9.03
1,SMOKE100,2.0,256497,17071,6.66

Results for SMOKDAY2

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
4,SMOKDAY2,9.0,184,27,14.67
2,SMOKDAY2,3.0,118181,16647,14.09
0,SMOKDAY2,1.0,32628,4372,13.40
3,SMOKDAY2,7.0,185,21,11.35
1,SMOKDAY2,2.0,13776,1497,10.87

Results for ECIGNOW3

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
4,ECIGNOW3,7.0,1123,159,14.16
5,ECIGNOW3,9.0,817,85,10.40
0,ECIGNOW3,1.0,339562,33444,9.85
3,ECIGNOW3,4.0,56513,4795,8.48
2,ECIGNOW3,3.0,11264,632,5.61
1,ECIGNOW3,2.0,13003,639,4.91

Results for USENOW3

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
3,USENOW3,7.0,481,49,10.19
0,USENOW3,1.0,7283,701,9.63
2,USENOW3,3.0,409890,38604,9.42
4,USENOW3,9.0,441,39,8.84
1,USENOW3,2.0,5207,442,8.49

Results for ALCDAY4

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
34,ALCDAY4,227.0,207,25,12.08
39,ALCDAY4,888.0,200380,23589,11.77
37,ALCDAY4,230.0,12898,1478,11.46
7,ALCDAY4,107.0,5849,596,10.19
38,ALCDAY4,777.0,2794,275,9.84
28,ALCDAY4,221.0,187,17,9.09
27,ALCDAY4,220.0,5790,502,8.67
40,ALCDAY4,999.0,1585,135,8.52
32,ALCDAY4,225.0,2696,213,7.90
33,ALCDAY4,226.0,165,13,7.88
8,ALCDAY4,201.0,34106,2677,7.85
6,ALCDAY4,106.0,1753,136,7.76
36,ALCDAY4,229.0,293,22,7.51
29,ALCDAY4,222.0,160,12,7.50
5,ALCDAY4,105.0,5455,405,7.42
22,ALCDAY4,215.0,5423,381,7.03
19,ALCDAY4,212.0,1629,112,6.88
10,ALCDAY4,203.0,14403,985,6.84
9,ALCDAY4,202.0,25203,1725,6.84
35,ALCDAY4,228.0,822,56,6.81
4,ALCDAY4,104.0,5559,368,6.62
1,ALCDAY4,101.0,19800,1311,6.62
17,ALCDAY4,210.0,6906,439,6.36
11,ALCDAY4,204.0,10906,691,6.34
31,ALCDAY4,224.0,191,12,6.28
24,ALCDAY4,217.0,81,5,6.17
12,ALCDAY4,205.0,10444,629,6.02
2,ALCDAY4,102.0,15819,945,5.97
13,ALCDAY4,206.0,3662,213,5.82
25,ALCDAY4,218.0,208,12,5.77
21,ALCDAY4,214.0,588,33,5.61
3,ALCDAY4,103.0,11366,634,5.58
14,ALCDAY4,207.0,2715,143,5.27
23,ALCDAY4,216.0,213,11,5.16
16,ALCDAY4,209.0,273,14,5.13
15,ALCDAY4,208.0,3103,156,5.03
30,ALCDAY4,223.0,68,3,4.41
20,ALCDAY4,213.0,99,2,2.02
0,ALCDAY4,100.0,1,0,0.00
18,ALCDAY4,211.0,38,0,0.00
26,ALCDAY4,219.0,10,0,0.00

Results for DIABETE4

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,DIABETE4,1.0,64586,14217,22.01
3,DIABETE4,4.0,11059,1480,13.38
4,DIABETE4,7.0,680,76,11.18
5,DIABETE4,9.0,89,8,8.99
2,DIABETE4,3.0,372683,26375,7.08
1,DIABETE4,2.0,3365,182,5.41

Results for CHCKDNY2

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,CHCKDNY2,1.0,23236,6756,29.08
2,CHCKDNY2,7.0,1542,316,20.49
3,CHCKDNY2,9.0,108,15,13.89
1,CHCKDNY2,2.0,427574,35251,8.24

Results for CVDSTRK3

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,CVDSTRK3,1.0,20102,7281,36.22
2,CVDSTRK3,7.0,959,267,27.84
3,CVDSTRK3,9.0,35,8,22.86
1,CVDSTRK3,2.0,431367,34782,8.06

Results for CHCCOPD3

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,CHCCOPD3,1.0,35991,9860,27.40
2,CHCCOPD3,7.0,1693,324,19.14
3,CHCCOPD3,9.0,89,16,17.98
1,CHCCOPD3,2.0,414686,32136,7.75

Results for ADDEPEV3

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
2,ADDEPEV3,7.0,1888,217,11.49
0,ADDEPEV3,1.0,94861,10827,11.41
3,ADDEPEV3,9.0,422,45,10.66
1,ADDEPEV3,2.0,355290,31249,8.80

Results for HAVARTH4

,feature,feature_value,total_people,heart_disease_cases,heart_disease_percent
0,HAVARTH4,1.0,155888,25630,16.44
2,HAVARTH4,7.0,2069,222,10.73
3,HAVARTH4,9.0,141,11,7.80
1,HAVARTH4,2.0,294363,16475,5.60

In [23]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

outcome = "_MICHD"

results = []

for predictor in predictors:
    temp = df[[predictor, outcome]].dropna()
    table = pd.crosstab(temp[predictor], temp[outcome])

    if table.shape[0] < 2 or table.shape[1] < 2:
        continue

    chi2, p_value, dof, expected = chi2_contingency(table)

    n = table.to_numpy().sum()
    min_dim = min(table.shape) - 1
    cramers_v = np.sqrt(chi2 / (n * min_dim)) if min_dim > 0 else np.nan

    results.append({
        "predictor": predictor,
        "chi2": chi2,
        "p_value": p_value,
        "statistically_significant": "yes" if p_value < 0.05 else "no",
        "cramers_v": cramers_v,
        "degrees_of_freedom": dof,
        "n": n
    })

significance_results_df = (
    pd.DataFrame(results)
    .sort_values(["p_value", "cramers_v"], ascending=[True, False])
    .reset_index(drop=True)
)

significance_results_df

,predictor,chi2,p_value,statistically_significant,cramers_v,degrees_of_freedom,n
0,_AGEG5YR,27606.608103,0.000000e+00,yes,0.247010,13,452464
1,GENHLTH,26206.111471,0.000000e+00,yes,0.240664,6,452461
2,EMPLOY1,23658.930506,0.000000e+00,yes,0.229493,8,449217
3,_RFHLTH,19814.332551,0.000000e+00,yes,0.209266,2,452464
4,CVDSTRK3,18348.354388,0.000000e+00,yes,0.201376,3,452463
5,CHCCOPD3,15270.544798,0.000000e+00,yes,0.183712,3,452459
6,DIABETE4,14755.853396,0.000000e+00,yes,0.180589,5,452462
7,HAVARTH4,14136.081915,0.000000e+00,yes,0.176756,3,452461
8,CHCKDNY2,11504.026612,0.000000e+00,yes,0.159454,3,452460
9,MARITAL,8890.847049,0.000000e+00,yes,0.140179,6,452457
10,SMOKE100,5823.018345,0.000000e+00,yes,0.117180,3,424075
11,INCOME3,5398.329666,0.000000e+00,yes,0.110346,12,443348
12,CHECKUP1,4028.452418,0.000000e+00,yes,0.094358,6,452464
13,WEIGHT2,3548.999189,0.000000e+00,yes,0.089775,627,440344
14,ALCDAY4,3087.239322,0.000000e+00,yes,0.086370,40,413848
15,_SEX,2051.832827,0.000000e+00,yes,0.067341,1,452464
16,EDUCA,1666.064331,0.000000e+00,yes,0.060681,6,452459
17,HEIGHT3,1200.929794,1.021419e-153,yes,0.052286,172,439289
18,ECIGNOW3,662.987579,4.933066e-141,yes,0.039623,5,422282
19,RENTHOM1,630.753245,3.418830e-135,yes,0.037337,4,452458
20,ADDEPEV3,616.171908,3.143868e-133,yes,0.036903,3,452461
21,SMOKDAY2,112.014017,2.706410e-23,yes,0.026059,4,164954
22,USENOW3,6.119708,1.903850e-01,no,0.003802,4,423302