**BRFSS Risk Factors for Heart Disease Data EDA**

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/brfss/brfss_survey_data_2024.csv")

# print first entries
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000001',2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000002',2.024000e+09,1.0,...,4.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
2,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000003',2.024000e+09,1.0,...,4.0,2.0,1.0,1.000000e+02,2.0,1.400000e+03,1.0,NaN,NaN,2.0
3,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000004',2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
4,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000005',2.024000e+09,1.0,...,3.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0

In [ ]:
# number of rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# print names of columns and stats on each column 
eda_table = pd.DataFrame({
    "feature": df.columns,
    "dtype": df.dtypes.astype(str),
    "unique_values": df.nunique(dropna=False).values,
    "missing_count": df.isna().sum().values,
    "missing_percent": (df.isna().mean().values * 100).round(2)
})

eda_table = eda_table.sort_values("missing_percent", ascending=False)
eda_table

Number of rows: 457670
Number of columns: 301

           feature    dtype  unique_values  missing_count  missing_percent
RCSGEND1  RCSGEND1  float64              1         457670           100.00
COLGHOUS  COLGHOUS  float64              2         457656           100.00
RCSXBRTH  RCSXBRTH  float64              1         457670           100.00
CSRVCTL2  CSRVCTL2  float64              7         457088            99.87
ICFQSTVR  ICFQSTVR  float64              5         456931            99.84
...            ...      ...            ...            ...              ...
DRNKANY6  DRNKANY6  float64              4              0             0.00
_DRNKWK3  _DRNKWK3  float64            283              0             0.00
_RFBING6  _RFBING6  float64              3              0             0.00
DROCDY4_  DROCDY4_  float64             37              1             0.00
_RFDRHV9  _RFDRHV9  float64              3              0             0.00

[301 rows x 5 columns]

In [10]:
df.describe()

,_STATE,FMONTH,DISPCODE,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
count,457670.000000,457670.000000,457670.000000,4.576700e+05,81730.0,81730.000000,14.0,81730.0,81730.0,81730.000000,...,393433.000000,406226.000000,457670.000000,4.576690e+05,457670.000000,4.576700e+05,457670.000000,179344.000000,179344.000000,414178.000000
mean,30.823537,6.426995,1118.669784,2.024007e+09,1.0,1.000171,1.0,1.0,2.0,1.001835,...,3.420252,8.468687,2.196764,1.000599e+02,1.948965,1.044393e+04,1.869063,2.336850,2.462223,1.999684
std,15.939364,3.356938,38.966920,7.488291e+03,0.0,0.013087,0.0,0.0,0.0,0.042801,...,0.792956,1.892208,2.226566,2.613717e+02,2.418721,3.016653e+04,2.414067,2.602255,2.814818,1.665037
min,1.000000,1.000000,1100.000000,2.024000e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,1.000000,1.000000,1.000000,5.397605e-79,1.000000,5.397605e-79,1.000000,1.000000,1.000000,1.000000
25%,18.000000,4.000000,1100.000000,2.024002e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,3.000000,9.000000,1.000000,5.397605e-79,1.000000,5.397605e-79,1.000000,1.000000,1.000000,1.000000
50%,31.000000,7.000000,1100.000000,2.024005e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,4.000000,9.000000,2.000000,3.000000e+00,1.000000,4.700000e+01,1.000000,1.000000,1.000000,2.000000
75%,44.000000,9.000000,1100.000000,2.024008e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,4.000000,9.000000,2.000000,2.900000e+01,1.000000,4.670000e+02,1.000000,2.000000,2.000000,2.000000
max,78.000000,12.000000,1200.000000,2.024044e+09,1.0,2.000000,1.0,1.0,2.0,2.000000,...,4.000000,9.000000,9.000000,9.000000e+02,9.000000,9.990000e+04,9.000000,9.000000,9.000000,9.000000